inorder, preorder, postorder, bfs
bcherny/frontend-interview-questions pull request #15
Opened 2018-09-10 19:25 UTC by albertywu

solution to tree traversal problem

2018-09-11 03:32 UTC, bcherny requested changes
Looks great overall - some minor comments.

2018-09-11 03:32 UTC, bcherny commented on coding-harder/TreeTraversal.js
> +  inorder() {
Should this take a function?

2018-09-11 03:32 UTC, bcherny commented on coding-harder/TreeTraversal.js
> +  preorder() {
Same here

2018-09-11 03:32 UTC, bcherny commented on coding-harder/TreeTraversal.js
> +  postorder() {
And here

2018-09-11 03:32 UTC, bcherny commented on coding-harder/TreeTraversal.js
> +  bfs() {
And here

2018-09-11 03:32 UTC, bcherny commented on coding-harder/TreeTraversal.js
> +  }
This is really nice! You might consider making this a generator and using `yield` to reduce some of this boilerplate!

2018-09-11 03:32 UTC, bcherny commented on coding-harder/TreeTraversal.js
> +    .from(bst.bfs())
Neat!!

2018-09-11 16:11 UTC, albertywu commented
done!

2018-09-12 04:42 UTC, bcherny approved these changes
Looking great! Thanks @albertywu!

2018-09-12 04:42 UTC, merged